dataset:
  predict_path: /root/1-TianFeng/test.json

model:
  model_path: /root/1-TianFeng/data/models/docred_joint/joint_multi_instance/model.ckpt
  tokenizer_path: /root/1-TianFeng/data/models/docred_joint/joint_multi_instance
  encoder_config_path: /root/1-TianFeng/data/models/docred_joint/joint_multi_instance

inference:
  test_batch_size: 1

distribution:
  gpus: []
  accelerator: 'auto'
  prepare_data_per_node: false

hydra:
  run:
    dir: /root/1-TianFeng/data/runs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  output_subdir: run_config